/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osym_Calculation_JNICalculator_JNICalculatorListener */

#ifndef _Included_org_osym_Calculation_JNICalculator_JNICalculatorListener
#define _Included_org_osym_Calculation_JNICalculator_JNICalculatorListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
