/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osym_Calculation_JNICalculator */

#ifndef _Included_org_osym_Calculation_JNICalculator
#define _Included_org_osym_Calculation_JNICalculator

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osym_Calculation_JNICalculator
 * Method:    run
 * Signature: ([[D[D[DDDDLorg/osym/Calculation/JNICalculator/JNICalculatorListener;)V
 */
JNIEXPORT void JNICALL Java_org_osym_Calculation_JNICalculator_run
    (JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jobject);

JNIEXPORT void JNICALL Java_org_osym_Calculation_JNICalculator_pause
    (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_org_osym_Calculation_JNICalculator_cancel
    (JNIEnv *,jobject);

#ifdef __cplusplus
}
#endif
#endif
